merge jobs back again as getting artifacts between them exeeds the rate limit (5gb+) and cause timeouts with fail

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,16 +13,12 @@ env:
   DOCKER_BUILDKIT: 1
 
 jobs:
-  prepare_and_base:
-    name: Build Base Images
+  build_all:
+    name: Build FFmpeg Win64
     runs-on: ubuntu-latest
     permissions:
       packages: write
-    outputs:
-      repo_lc: ${{ steps.images.outputs.repo_lc }}
-      base: ${{ steps.images.outputs.base }}
-      target_base: ${{ steps.images.outputs.target_base }}
-      variant: ${{ steps.images.outputs.variant }}
+      contents: write
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -65,19 +61,11 @@ jobs:
           cache-from: type=registry,ref=${{ steps.images.outputs.target_base }}-cache
           cache-to: type=registry,mode=max,ref=${{ steps.images.outputs.target_base }}-cache
 
-  generate_and_cache:
-    name: Generate and Cache
-    needs: prepare_and_base
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
       - name: Get Download Cache Key
         id: dl_cache
         run: echo "key=$(./util/get_dl_cache_tag.sh)" >> $GITHUB_OUTPUT
 
-      - name: Restore/Update Download Cache
+      - name: Restore Download Cache
         uses: actions/cache@v4
         with:
           path: .cache/downloads
@@ -92,64 +80,37 @@ jobs:
       - name: Generate Dockerfile
         run: ./generate.sh win64 nonfree
 
-      - name: Save build context
-        uses: actions/upload-artifact@v4
-        with:
-          name: build-context
-          path: |
-            ./
-            .cache/
-          include-hidden-files: true
-          retention-days: 1 # store it only until the end of the workflow
+#      - name: Save build context
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: build-context
+#          path: |
+#            ./
+#            .cache/
+#          include-hidden-files: true
+#          retention-days: 1 # store it only until the end of the workflow
+#
+#            # ./Dockerfile
+#            # ./build.sh
+#            # ./util/
+#            # ./scripts.d/
+#            # ./variants/
+#            # ./.cache/downloads/ # sources if don't use external caches
 
-            # ./Dockerfile
-            # ./build.sh
-            # ./util/
-            # ./scripts.d/
-            # ./variants/
-            # ./.cache/downloads/ # sources if don't use external caches
+#      - name: Debug Context
+#        run: |
+#          echo "Checking context..."
+#          pwd
+#          ls -a
+#          ls -R .cache/downloads/ | grep zvbi || echo "STILL MISSING"
+#          # if the file is not here, it means it was not downloaded or was not transferred by an artifact
 
-  build_ffmpeg:
-    name: Compile FFmpeg
-    needs: [prepare_and_base, generate_and_cache]
-    runs-on: ubuntu-latest
-    permissions:
-      packages: write
-      contents: write
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-
-      - name: Download build context
-        uses: actions/download-artifact@v4
-        with:
-          name: build-context
-          path: . 
-
-      - name: Setup Buildx
-        uses: docker/setup-buildx-action@v3
-
-      - name: Login to Docker
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ github.token }}
-
-      - name: Debug Context
-        run: |
-          echo "Checking context..."
-          pwd
-          ls -a
-          ls -R .cache/downloads/ | grep zvbi || echo "STILL MISSING"
-          # if the file is not here, it means it was not downloaded or was not transferred by an artifact
-
-      - name: Build and Export
+      - name: Build and Export FFmpeg
         uses: docker/build-push-action@v6
         with:
           context: .
           push: true
-          tags: ${{ needs.prepare_and_base.outputs.variant }}
+          tags: ${{ steps.images.outputs.variant }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
           # Configuring export:
@@ -173,8 +134,6 @@ jobs:
         run: |
           RELDATE="$(date +'%Y-%m-%d %H:%M')"
           TAGNAME="autobuild-$(date +'%Y-%m-%d-%H-%M')"
-          # check for file availability before release
-          ls -R artifacts/
           (cd artifacts && sha256sum *.7z > checksums.sha256)
           gh release create "$TAGNAME" --target "${{ github.ref_name }}" \
             --title "Auto-Build $RELDATE" artifacts/*.7z artifacts/checksums.sha256
